name: Announcements for changes
about: This issue template should be used only for maintainers of the project
title: ''
labels: announcement
assignees: ''

- type: textarea
  id: changeDesc
  attributes:
    label: Change description
  validations:
    required: true

- type: textarea
  id: whyThisChange
  attributes:
    label: Why should this change be added?
  validations:
    required: true

- type: textarea
  id: additionalContext
  attributes:
    label: Additional context
  validations:
    required: false


