name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

- type: textarea
  id: bugDesc
  attributes:
    description: A clear and concise description of what the bug is.
  validations:
    required: true


- type: textarea
  id: reproduceSteps
  attributes:
    title: To Reproduce
    value: |
      Steps to reproduce the behavior:
      1.
      2.
      3. 
      4.
  validations:
    required: true

- type: textarea
  id: expectedBehavior
  attributes:
    title: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  id: desktop
  attributes:
    title: Desktop
    value: |
      - OS: [e.g. iOS]
      - Browser [e.g. chrome, safari]
      - Version [e.g. 22]]
  validations:
    required: true

- type: textarea
  id: additionalContext
  attributes:
    title: Additional context
    description: Add any other context about the problem here.
