name: Feature request
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''

- type: textarea
  id: featureRequestRelatedToProblem
  attributes:
    title: Is your feature request related to a problem? Please describe.
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: true

- type: textarea
  id: solutionDesc
  attributions:
    title: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true

- type: textarea
  id: alternativesDesc
  attributions:
    title: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: true

- type: textarea
  id: additionalContext
  attributions:
    title: Additional context
    description: Add any other context or screenshots about the feature request here.
